# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://globalaisummit.github.io
title: Global AI Summit
email: kimhj9502@gmail.com
author: Hyeonjin Kim
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2019 Hyeonjin Kim. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: CTL, Seoul National University
    url: https://ctl.snu.ac.kr/ko/introduction/map
